//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MasterPage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MasterPage() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.MasterPage", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add company.
        /// </summary>
        internal static string AddMaker {
            get {
                return ResourceManager.GetString("AddMaker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add product.
        /// </summary>
        internal static string AddProduct {
            get {
                return ResourceManager.GetString("AddProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced options.
        /// </summary>
        internal static string advSearchTooltip {
            get {
                return ResourceManager.GetString("advSearchTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string bottomText {
            get {
                return ResourceManager.GetString("bottomText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bulgarian.
        /// </summary>
        internal static string Bulgarian {
            get {
                return ResourceManager.GetString("Bulgarian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 100%.
        /// </summary>
        internal static string cbMaxWidth {
            get {
                return ResourceManager.GetString("cbMaxWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currently min./max. :.
        /// </summary>
        internal static string currently {
            get {
                return ResourceManager.GetString("currently", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit rights.
        /// </summary>
        internal static string EditRoles {
            get {
                return ResourceManager.GetString("EditRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit suggestions.
        /// </summary>
        internal static string EditSuggestions {
            get {
                return ResourceManager.GetString("EditSuggestions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Javascript is necessary in order for this site to run properly. Please enable it!.
        /// </summary>
        internal static string errJavaScript {
            get {
                return ResourceManager.GetString("errJavaScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type a number for maximum width or check &quot;100%&quot;..
        /// </summary>
        internal static string errMaxWidth {
            get {
                return ResourceManager.GetString("errMaxWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type a number for minimum width..
        /// </summary>
        internal static string errMinWidth {
            get {
                return ResourceManager.GetString("errMinWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FAQ.
        /// </summary>
        internal static string FAQ {
            get {
                return ResourceManager.GetString("FAQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guide.
        /// </summary>
        internal static string Guide {
            get {
                return ResourceManager.GetString("Guide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hi,.
        /// </summary>
        internal static string Hi {
            get {
                return ResourceManager.GetString("Hi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hi, Guest!.
        /// </summary>
        internal static string HiGuest {
            get {
                return ResourceManager.GetString("HiGuest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language :.
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to log in.
        /// </summary>
        internal static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to log out.
        /// </summary>
        internal static string logout {
            get {
                return ResourceManager.GetString("logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum :.
        /// </summary>
        internal static string MaxWidth {
            get {
                return ResourceManager.GetString("MaxWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu.
        /// </summary>
        internal static string Menu {
            get {
                return ResourceManager.GetString("Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Private messages.
        /// </summary>
        internal static string Messages {
            get {
                return ResourceManager.GetString("Messages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum :.
        /// </summary>
        internal static string MinWidth {
            get {
                return ResourceManager.GetString("MinWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My reports.
        /// </summary>
        internal static string MyReports {
            get {
                return ResourceManager.GetString("MyReports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notifications.
        /// </summary>
        internal static string Notifies {
            get {
                return ResourceManager.GetString("Notifies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to options.
        /// </summary>
        internal static string optionslbl {
            get {
                return ResourceManager.GetString("optionslbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to or.
        /// </summary>
        internal static string or {
            get {
                return ResourceManager.GetString("or", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        internal static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to register.
        /// </summary>
        internal static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        internal static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rules.
        /// </summary>
        internal static string Rules {
            get {
                return ResourceManager.GetString("Rules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products quality through consumer&apos;s focus.
        /// </summary>
        internal static string SiteMotto {
            get {
                return ResourceManager.GetString("SiteMotto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suggestions.
        /// </summary>
        internal static string Suggestions {
            get {
                return ResourceManager.GetString("Suggestions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New content.
        /// </summary>
        internal static string tooltipImgNewContent {
            get {
                return ResourceManager.GetString("tooltipImgNewContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have unread message(s).
        /// </summary>
        internal static string tooltipImgNewMail {
            get {
                return ResourceManager.GetString("tooltipImgNewMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have new reply to report.
        /// </summary>
        internal static string tooltipImgNewReplyToReport {
            get {
                return ResourceManager.GetString("tooltipImgNewReplyToReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New suggestion and/or comment has been sent to you.
        /// </summary>
        internal static string tooltipImgNewSuggComment {
            get {
                return ResourceManager.GetString("tooltipImgNewSuggComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have unread system message(s).
        /// </summary>
        internal static string tooltipImgNewSysMsg {
            get {
                return ResourceManager.GetString("tooltipImgNewSysMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have new warning(s).
        /// </summary>
        internal static string tooltipImgNewWarning {
            get {
                return ResourceManager.GetString("tooltipImgNewWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose site width.
        /// </summary>
        internal static string Width {
            get {
                return ResourceManager.GetString("Width", resourceCulture);
            }
        }
    }
}
