//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Validate {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Validate() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Validate", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to and.
        /// </summary>
        internal static string and {
            get {
                return ResourceManager.GetString("and", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to characters.
        /// </summary>
        internal static string characters {
            get {
                return ResourceManager.GetString("characters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot send message to that user..
        /// </summary>
        internal static string errCantSendMsgToUser {
            get {
                return ResourceManager.GetString("errCantSendMsgToUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The description should be between.
        /// </summary>
        internal static string errDescrLength {
            get {
                return ResourceManager.GetString("errDescrLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is already subvariant with that name..
        /// </summary>
        internal static string errDuplicateSubVariantName {
            get {
                return ResourceManager.GetString("errDuplicateSubVariantName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A variant with the specified name already exists..
        /// </summary>
        internal static string errDuplicateVariantName {
            get {
                return ResourceManager.GetString("errDuplicateVariantName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id should be between.
        /// </summary>
        internal static string errIdLength {
            get {
                return ResourceManager.GetString("errIdLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect current password..
        /// </summary>
        internal static string errIncCurrPass {
            get {
                return ResourceManager.GetString("errIncCurrPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect name format..
        /// </summary>
        internal static string errIncNameFormat {
            get {
                return ResourceManager.GetString("errIncNameFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid email adress..
        /// </summary>
        internal static string errInvMail {
            get {
                return ResourceManager.GetString("errInvMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid site address format..
        /// </summary>
        internal static string errInvSiteFormat {
            get {
                return ResourceManager.GetString("errInvSiteFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The description length must be between.
        /// </summary>
        internal static string errLocalWordForLengthDescription {
            get {
                return ResourceManager.GetString("errLocalWordForLengthDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name length must be between.
        /// </summary>
        internal static string errLocalWordForLengthName {
            get {
                return ResourceManager.GetString("errLocalWordForLengthName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The signature length must be between.
        /// </summary>
        internal static string errLocalWordForLengthSignature {
            get {
                return ResourceManager.GetString("errLocalWordForLengthSignature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The subject length must be between.
        /// </summary>
        internal static string errLocalWordForLengthSubject {
            get {
                return ResourceManager.GetString("errLocalWordForLengthSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type a description..
        /// </summary>
        internal static string errLocalWordForTypeItDescription {
            get {
                return ResourceManager.GetString("errLocalWordForTypeItDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type a name..
        /// </summary>
        internal static string errLocalWordForTypeItName {
            get {
                return ResourceManager.GetString("errLocalWordForTypeItName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type signature..
        /// </summary>
        internal static string errLocalWordForTypeItSignature {
            get {
                return ResourceManager.GetString("errLocalWordForTypeItSignature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type a subject..
        /// </summary>
        internal static string errLocalWordForTypeItSubject {
            get {
                return ResourceManager.GetString("errLocalWordForTypeItSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t send messages to yourself..
        /// </summary>
        internal static string errMsgCantSendToSelf {
            get {
                return ResourceManager.GetString("errMsgCantSendToSelf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name length must be between.
        /// </summary>
        internal static string errNameLength {
            get {
                return ResourceManager.GetString("errNameLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to That name is taken already..
        /// </summary>
        internal static string errNameTaken {
            get {
                return ResourceManager.GetString("errNameTaken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use only alphabetical characters and/or numbers for new user password..
        /// </summary>
        internal static string errNewUserPass {
            get {
                return ResourceManager.GetString("errNewUserPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No such user..
        /// </summary>
        internal static string errNoSuchUser {
            get {
                return ResourceManager.GetString("errNoSuchUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number must be positive..
        /// </summary>
        internal static string errParseToLong {
            get {
                return ResourceManager.GetString("errParseToLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password cannot contain username..
        /// </summary>
        internal static string errPassCannotContainUsername {
            get {
                return ResourceManager.GetString("errPassCannotContainUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use alphabetical characters and/or numbers for password..
        /// </summary>
        internal static string errPassChars {
            get {
                return ResourceManager.GetString("errPassChars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New user password and repeat password fields do not match..
        /// </summary>
        internal static string errPassFieldsDoNotMatch {
            get {
                return ResourceManager.GetString("errPassFieldsDoNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password length should be between.
        /// </summary>
        internal static string errPassLength {
            get {
                return ResourceManager.GetString("errPassLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to That name is taken already. Add the company name in front..
        /// </summary>
        internal static string errProdNameTaken {
            get {
                return ResourceManager.GetString("errProdNameTaken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website URL is too long..
        /// </summary>
        internal static string errSiteLength {
            get {
                return ResourceManager.GetString("errSiteLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text should be between.
        /// </summary>
        internal static string errTextLength {
            get {
                return ResourceManager.GetString("errTextLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type your password..
        /// </summary>
        internal static string errTypeCurrPass {
            get {
                return ResourceManager.GetString("errTypeCurrPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type a description!.
        /// </summary>
        internal static string errTypeDescr {
            get {
                return ResourceManager.GetString("errTypeDescr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type an email adress..
        /// </summary>
        internal static string errTypeMail {
            get {
                return ResourceManager.GetString("errTypeMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type a name!.
        /// </summary>
        internal static string errTypeName {
            get {
                return ResourceManager.GetString("errTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type a number..
        /// </summary>
        internal static string errTypeNumber {
            get {
                return ResourceManager.GetString("errTypeNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type a password..
        /// </summary>
        internal static string errTypePass {
            get {
                return ResourceManager.GetString("errTypePass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type a password for new user..
        /// </summary>
        internal static string errTypePassForNewUser {
            get {
                return ResourceManager.GetString("errTypePassForNewUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Populate the &quot;repeat password&quot; field..
        /// </summary>
        internal static string errTypeRepPass {
            get {
                return ResourceManager.GetString("errTypeRepPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type an URL..
        /// </summary>
        internal static string errTypeSite {
            get {
                return ResourceManager.GetString("errTypeSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type text..
        /// </summary>
        internal static string errTypeText {
            get {
                return ResourceManager.GetString("errTypeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type the user to which you want to send message..
        /// </summary>
        internal static string errTypeUserToSendMsg {
            get {
                return ResourceManager.GetString("errTypeUserToSendMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to That name is already taken..
        /// </summary>
        internal static string errUserNameTaken {
            get {
                return ResourceManager.GetString("errUserNameTaken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There should not be words longer than.
        /// </summary>
        internal static string errWordsLength {
            get {
                return ResourceManager.GetString("errWordsLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to length should be between.
        /// </summary>
        internal static string shouldBeBetween {
            get {
                return ResourceManager.GetString("shouldBeBetween", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to symbols.
        /// </summary>
        internal static string symbols {
            get {
                return ResourceManager.GetString("symbols", resourceCulture);
            }
        }
    }
}
