//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class WebMethods {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WebMethods() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.WebMethods", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to by :.
        /// </summary>
        internal static string by {
            get {
                return ResourceManager.GetString("by", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment reported to administrators! Number of remaining comments which can be marked as violation :.
        /// </summary>
        internal static string CommentMarkedSpam {
            get {
                return ResourceManager.GetString("CommentMarkedSpam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opinion/comment rated!.
        /// </summary>
        internal static string CommentRated {
            get {
                return ResourceManager.GetString("CommentRated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opinions :.
        /// </summary>
        internal static string Comments {
            get {
                return ResourceManager.GetString("Comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opinion added!.
        /// </summary>
        internal static string CommentToSuggestionWritten {
            get {
                return ResourceManager.GetString("CommentToSuggestionWritten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment added!.
        /// </summary>
        internal static string CommToTopicAdded {
            get {
                return ResourceManager.GetString("CommToTopicAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description :.
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not entered..
        /// </summary>
        internal static string DescrNotEntered {
            get {
                return ResourceManager.GetString("DescrNotEntered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot modify this topic..
        /// </summary>
        internal static string errAdmCantModifTopic {
            get {
                return ResourceManager.GetString("errAdmCantModifTopic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot edit this comment!.
        /// </summary>
        internal static string errAdmCantModifTopicComm {
            get {
                return ResourceManager.GetString("errAdmCantModifTopicComm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have already rated this opinion!.
        /// </summary>
        internal static string errAlreadyRated {
            get {
                return ResourceManager.GetString("errAlreadyRated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot delete the comment!.
        /// </summary>
        internal static string errCantDelTopicComm {
            get {
                return ResourceManager.GetString("errCantDelTopicComm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot mark administrator opinions!.
        /// </summary>
        internal static string errCantMarkAdminForSPam {
            get {
                return ResourceManager.GetString("errCantMarkAdminForSPam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot mark administrator suggestions!&quot;.
        /// </summary>
        internal static string errCantMarkAdminSuggForSpam {
            get {
                return ResourceManager.GetString("errCantMarkAdminSuggForSpam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot mark opinions..
        /// </summary>
        internal static string errCantMarkCommSpam {
            get {
                return ResourceManager.GetString("errCantMarkCommSpam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot mark suggestions..
        /// </summary>
        internal static string errCantMarkSuggAsSpam {
            get {
                return ResourceManager.GetString("errCantMarkSuggAsSpam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot rate opinions/comments..
        /// </summary>
        internal static string errCantRate {
            get {
                return ResourceManager.GetString("errCantRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot rate administrator opinions/comments!.
        /// </summary>
        internal static string errCantRateAdminComms {
            get {
                return ResourceManager.GetString("errCantRateAdminComms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot rate your own opinions/comments!.
        /// </summary>
        internal static string errCantRateMyComms {
            get {
                return ResourceManager.GetString("errCantRateMyComms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot send messages..
        /// </summary>
        internal static string errCantSendMsg {
            get {
                return ResourceManager.GetString("errCantSendMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot send messages to administrators!.
        /// </summary>
        internal static string errCantSendMsgToAdmin {
            get {
                return ResourceManager.GetString("errCantSendMsgToAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot send messages to guests!.
        /// </summary>
        internal static string errCantSendMsgToGuest {
            get {
                return ResourceManager.GetString("errCantSendMsgToGuest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot send messages to yourself!.
        /// </summary>
        internal static string errCantSendMsgToUrself {
            get {
                return ResourceManager.GetString("errCantSendMsgToUrself", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot send message to that user!.
        /// </summary>
        internal static string errCantSendMsgToUser {
            get {
                return ResourceManager.GetString("errCantSendMsgToUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot send reports!.
        /// </summary>
        internal static string errCantSendReport {
            get {
                return ResourceManager.GetString("errCantSendReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot write opinions..
        /// </summary>
        internal static string errCantWrite {
            get {
                return ResourceManager.GetString("errCantWrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The description is same as old!.
        /// </summary>
        internal static string errChangeTopicComm {
            get {
                return ResourceManager.GetString("errChangeTopicComm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System error incurred! Request coudn`t be handled..
        /// </summary>
        internal static string errExceptionMsg {
            get {
                return ResourceManager.GetString("errExceptionMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in, in order to send messages..
        /// </summary>
        internal static string errLogInSendMsg {
            get {
                return ResourceManager.GetString("errLogInSendMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in, in order to mark suggestions..
        /// </summary>
        internal static string errLogInToMarkSuggAsSpam {
            get {
                return ResourceManager.GetString("errLogInToMarkSuggAsSpam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in, in order to rate opinions..
        /// </summary>
        internal static string errLogInToRate {
            get {
                return ResourceManager.GetString("errLogInToRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in, in order to reply to opinions..
        /// </summary>
        internal static string errLogInToReply {
            get {
                return ResourceManager.GetString("errLogInToReply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in, in order to mark opinions..
        /// </summary>
        internal static string errLogInToSpam {
            get {
                return ResourceManager.GetString("errLogInToSpam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, the maximum number of opinions which you can post about this product is reached..
        /// </summary>
        internal static string errMaxNumCommReached {
            get {
                return ResourceManager.GetString("errMaxNumCommReached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot send reports, because your maximum non-resolved reports limit is reached..
        /// </summary>
        internal static string errMaxRepLimitReached {
            get {
                return ResourceManager.GetString("errMaxRepLimitReached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum reply level reached! This opinion cannot have sub-opinions..
        /// </summary>
        internal static string errMaxReplyLvl {
            get {
                return ResourceManager.GetString("errMaxReplyLvl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have reached maximum number of active violation reports. You have to wait until you can mark opinions..
        /// </summary>
        internal static string errMaxSpamReached {
            get {
                return ResourceManager.GetString("errMaxSpamReached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have reached maximum number of active violation reports. You have to wait until you can mark suggestions..
        /// </summary>
        internal static string errMaxSpamReachedSugg {
            get {
                return ResourceManager.GetString("errMaxSpamReachedSugg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have reached maximum number of active suggestions..
        /// </summary>
        internal static string errMaxTypeSuggNumberReached {
            get {
                return ResourceManager.GetString("errMaxTypeSuggNumberReached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum time between posting opinions is.
        /// </summary>
        internal static string errMinTimeBetwPostingComm {
            get {
                return ResourceManager.GetString("errMinTimeBetwPostingComm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to min, you can post after.
        /// </summary>
        internal static string errMinTimeBetwPostingComm2 {
            get {
                return ResourceManager.GetString("errMinTimeBetwPostingComm2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to min.
        /// </summary>
        internal static string errMinTimeBetwPostingComm3 {
            get {
                return ResourceManager.GetString("errMinTimeBetwPostingComm3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum time between posting comment is.
        /// </summary>
        internal static string errMinTimeBetwPostingTopicComm {
            get {
                return ResourceManager.GetString("errMinTimeBetwPostingTopicComm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot receive notifications for more than.
        /// </summary>
        internal static string errNotifLimit {
            get {
                return ResourceManager.GetString("errNotifLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to types.
        /// </summary>
        internal static string errNotifLimit2 {
            get {
                return ResourceManager.GetString("errNotifLimit2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No such user..
        /// </summary>
        internal static string errNoUser {
            get {
                return ResourceManager.GetString("errNoUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This link is already added!.
        /// </summary>
        internal static string errProdLinkDuplicating {
            get {
                return ResourceManager.GetString("errProdLinkDuplicating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect link format..
        /// </summary>
        internal static string errProductLinkFormat {
            get {
                return ResourceManager.GetString("errProductLinkFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can start new topic after.
        /// </summary>
        internal static string errTimeAddTopic {
            get {
                return ResourceManager.GetString("errTimeAddTopic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minutes..
        /// </summary>
        internal static string errTimeAddTopic2 {
            get {
                return ResourceManager.GetString("errTimeAddTopic2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect topic subject format..
        /// </summary>
        internal static string errTopicSubjectFormat {
            get {
                return ResourceManager.GetString("errTopicSubjectFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type a report..
        /// </summary>
        internal static string errTypeReport {
            get {
                return ResourceManager.GetString("errTypeReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update description!.
        /// </summary>
        internal static string errUpdateDescription {
            get {
                return ResourceManager.GetString("errUpdateDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update topic subject or description..
        /// </summary>
        internal static string errUpdateTopic {
            get {
                return ResourceManager.GetString("errUpdateTopic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write comment!.
        /// </summary>
        internal static string errWriteComment {
            get {
                return ResourceManager.GetString("errWriteComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write a message!.
        /// </summary>
        internal static string errWriteMessage {
            get {
                return ResourceManager.GetString("errWriteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write opinion!.
        /// </summary>
        internal static string errWriteOpinion {
            get {
                return ResourceManager.GetString("errWriteOpinion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to for :.
        /// </summary>
        internal static string for1 {
            get {
                return ResourceManager.GetString("for1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From :.
        /// </summary>
        internal static string From {
            get {
                return ResourceManager.GetString("From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid subject length!.
        /// </summary>
        internal static string InvalidSubjectLength {
            get {
                return ResourceManager.GetString("InvalidSubjectLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to maker.
        /// </summary>
        internal static string maker {
            get {
                return ResourceManager.GetString("maker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Companies with similar names.
        /// </summary>
        internal static string MakersWithSimNames {
            get {
                return ResourceManager.GetString("MakersWithSimNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message sent!.
        /// </summary>
        internal static string MessageSent {
            get {
                return ResourceManager.GetString("MessageSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Subject..
        /// </summary>
        internal static string NoSubject {
            get {
                return ResourceManager.GetString("NoSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opinion reported to administrators! Number of remaining opinions which can be marked as violation :.
        /// </summary>
        internal static string OpinionMarkedSpam {
            get {
                return ResourceManager.GetString("OpinionMarkedSpam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to product.
        /// </summary>
        internal static string product {
            get {
                return ResourceManager.GetString("product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product link added!.
        /// </summary>
        internal static string ProductLinkAdded {
            get {
                return ResourceManager.GetString("ProductLinkAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link deleted!.
        /// </summary>
        internal static string ProductLinkDeleted {
            get {
                return ResourceManager.GetString("ProductLinkDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link description updated!.
        /// </summary>
        internal static string ProductLinkDescriptionChanged {
            get {
                return ResourceManager.GetString("ProductLinkDescriptionChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link reported to administrators! Number of remaining links which can be marked as violation :.
        /// </summary>
        internal static string ProductLinkMarkedAsSpam {
            get {
                return ResourceManager.GetString("ProductLinkMarkedAsSpam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products with similar names.
        /// </summary>
        internal static string ProductsWithSimNames {
            get {
                return ResourceManager.GetString("ProductsWithSimNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rating :.
        /// </summary>
        internal static string Rating {
            get {
                return ResourceManager.GetString("Rating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reply sent!.
        /// </summary>
        internal static string ReplySent {
            get {
                return ResourceManager.GetString("ReplySent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reply sent!.
        /// </summary>
        internal static string ReplyToReportSent {
            get {
                return ResourceManager.GetString("ReplyToReportSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report sent! Remaining number reports which can be sent :.
        /// </summary>
        internal static string ReportSent {
            get {
                return ResourceManager.GetString("ReportSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You signed for notifications when new products are added to this company..
        /// </summary>
        internal static string SignNotifOnMaker {
            get {
                return ResourceManager.GetString("SignNotifOnMaker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You signed for notifications when new opinions are written to this product..
        /// </summary>
        internal static string SignNotifOnProduct {
            get {
                return ResourceManager.GetString("SignNotifOnProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You signed for notifications when new topics are started in this forum..
        /// </summary>
        internal static string SignNotifOnProductForum {
            get {
                return ResourceManager.GetString("SignNotifOnProductForum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You signed for notifications when new comments are written in this topic..
        /// </summary>
        internal static string SignNotifOnProductTopic {
            get {
                return ResourceManager.GetString("SignNotifOnProductTopic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status :.
        /// </summary>
        internal static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suggestion reported to administrators! Number of remaining suggestions which can be marked as violation :.
        /// </summary>
        internal static string SuggestionMarkedAsSpam {
            get {
                return ResourceManager.GetString("SuggestionMarkedAsSpam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment changed!.
        /// </summary>
        internal static string TopicCommUpdated {
            get {
                return ResourceManager.GetString("TopicCommUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Topic posted!.
        /// </summary>
        internal static string topicCreated {
            get {
                return ResourceManager.GetString("topicCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Topic updated!.
        /// </summary>
        internal static string TopicUpdated {
            get {
                return ResourceManager.GetString("TopicUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer created!.
        /// </summary>
        internal static string TransferCreated {
            get {
                return ResourceManager.GetString("TransferCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type :.
        /// </summary>
        internal static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suggestion for.
        /// </summary>
        internal static string TypeSuggestionSent {
            get {
                return ResourceManager.GetString("TypeSuggestionSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sent to.
        /// </summary>
        internal static string TypeSuggestionSent2 {
            get {
                return ResourceManager.GetString("TypeSuggestionSent2", resourceCulture);
            }
        }
    }
}
